// app.jsx — Jaxon Stickler portfolio shell.
// Views: about (landing + diagram) · index (horizontal grid) · project

const { useState, useEffect, useRef } = React;

const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "locationStyle": "both",
  "indexCardMode": "title",
  "imageLimit": 6,
  "navPosition": "bottom-left",
  "bubbleOpacity": 1,
  "bubbleNavGraphic": false,
  "nodesLocked": true
} /*EDITMODE-END*/;

// hover readout for the diagram — positioned dynamically below the bio panel
function KeepAlive({ active, children }) {
  // Keeps a subtree mounted (images/iframes stay loaded) but visually removed
  // when inactive — so switching pages never re-downloads or re-renders it.
  return <div style={{ display: active ? 'contents' : 'none' }}>{children}</div>;
}

function DiagramReadout({ p, top }) {
  return (
    <div style={{
      position: 'fixed', left: 43, top: top, width: 300, zIndex: 26, pointerEvents: 'none',
      fontFamily: FONT, color: '#fff', fontSize: 12, lineHeight: 1.5,
      opacity: p ? 1 : 0, transform: p ? 'translateY(0)' : 'translateY(6px)',
      transition: 'opacity .3s ease, transform .3s ease',
      textShadow: '0 1px 8px rgba(0,0,0,0.9)'
    }}>
      {p &&
      <React.Fragment>
          <div style={{ fontWeight: 600, letterSpacing: '0.04em' }}>{p.title}</div>
          <div style={{ opacity: 0.7 }}>{p.year}</div>
        </React.Fragment>
      }
    </div>);

}

// hover readout for the index grid (when cards are off)
function IndexReadout({ p }) {
  return (
    <div style={{
      position: 'fixed', left: 43, bottom: 78, width: 320, zIndex: 38, pointerEvents: 'none',
      fontFamily: FONT, color: '#fff', fontSize: 12, lineHeight: 1.5,
      opacity: p ? 1 : 0, transform: p ? 'translateY(0)' : 'translateY(6px)',
      transition: 'opacity .3s ease, transform .3s ease',
      textShadow: '0 1px 6px rgba(0,0,0,0.7)'
    }}>
      {p &&
      <React.Fragment>
          <div style={{ fontWeight: 600, letterSpacing: '0.04em' }}>{p.title}</div>
          <div style={{ opacity: 0.65 }}>{p.year}</div>
          {p.keywords && <div style={{ opacity: 0.5, marginTop: 6 }}>{p.keywords.join(', ')}</div>}
        </React.Fragment>
      }
    </div>);

}

// Collects the authored arrangement out of localStorage and emits a layout.js
// snapshot. Tries a real file download (works on a hosted/real browser); falls
// back to an on-screen copy box when the sandboxed preview blocks downloads.
const LAYOUT_KEY_RE = /^(diagram-node-pos|gallery-order-|preview-count-|index-project-order|project-column-order|large-entity-pos|project-links-|image-sizes-)/;

function buildLayoutFile() {
  var snap = {};
  try {
    for (var i = 0; i < localStorage.length; i++) {
      var k = localStorage.key(i);
      if (LAYOUT_KEY_RE.test(k)) snap[k] = localStorage.getItem(k);
    }
  } catch (_) {}
  var header =
    '// BAKED LAYOUT SNAPSHOT — generated by the Export layout button.\n' +
    '// Drop this file into the site root (next to index.html) to ship the\n' +
    '// authored arrangement. Do not hand-edit.\n' +
    '// Captured: ' + new Date().toISOString() + '\n';
  var body = 'window.BAKED_LAYOUT = ' + JSON.stringify(snap, null, 2) + ';\n\n' +
    'window.layoutGet = function (key) {\n' +
    '  try {\n' +
    '    var v = localStorage.getItem(key);\n' +
    '    if (v !== null && v !== undefined) return v;\n' +
    '  } catch (_) {}\n' +
    '  if (window.BAKED_LAYOUT && Object.prototype.hasOwnProperty.call(window.BAKED_LAYOUT, key)) {\n' +
    '    return window.BAKED_LAYOUT[key];\n' +
    '  }\n' +
    '  return null;\n' +
    '};\n';
  return { text: header + body, count: Object.keys(snap).length };
}

function LayoutExport() {
  const [box, setBox] = useState(null); // { text, count } when showing fallback
  const taRef = useRef(null);
  const doExport = () => {
    const out = buildLayoutFile();
    try {
      const blob = new Blob([out.text], { type: 'text/javascript' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = 'layout.js';
      document.body.appendChild(a); a.click(); a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 4000);
    } catch (_) {}
    // always show the copy box too, so it works even if the download was blocked
    setBox(out);
    setTimeout(() => { if (taRef.current) { taRef.current.focus(); taRef.current.select(); } }, 30);
  };
  const copy = () => {
    if (taRef.current) {
      taRef.current.focus(); taRef.current.select();
      try { document.execCommand('copy'); } catch (_) {}
      try { navigator.clipboard && navigator.clipboard.writeText(box.text); } catch (_) {}
    }
  };
  return (
    <div>
      <button onClick={doExport} data-clickable style={{
        width: '100%', padding: '9px 12px', marginTop: 4,
        background: '#fff', color: '#000', border: 'none', borderRadius: 7,
        fontFamily: FONT, fontSize: 11, fontWeight: 600, letterSpacing: '0.04em',
        textTransform: 'uppercase', cursor: 'pointer',
      }}>Export layout</button>
      {box &&
      <div style={{ marginTop: 8 }}>
          <div style={{ fontFamily: FONT, fontSize: 10, opacity: 0.7, marginBottom: 5, lineHeight: 1.4 }}>
            {box.count} item{box.count === 1 ? '' : 's'} captured. A file <b>layout.js</b> was downloaded — replace the one in your site folder with it. If no download appeared, copy the text below into <b>layout.js</b>.
          </div>
          <textarea ref={taRef} readOnly value={box.text} onFocus={(e) => e.target.select()} style={{
            width: '100%', height: 90, resize: 'vertical', fontFamily: 'monospace', fontSize: 9,
            background: 'rgba(255,255,255,0.06)', color: '#fff',
            border: '1px solid rgba(255,255,255,0.18)', borderRadius: 6, padding: 7, boxSizing: 'border-box',
          }} />
          <button onClick={copy} data-clickable style={{
            marginTop: 5, padding: '5px 10px', background: 'transparent', color: '#fff',
            border: '1px solid rgba(255,255,255,0.3)', borderRadius: 6,
            fontFamily: FONT, fontSize: 10, cursor: 'pointer',
          }}>Copy to clipboard</button>
        </div>
      }
    </div>
  );
}

function App() {
  const [t, setTweak] = useTweaks(TWEAK_DEFAULTS);
  const isMobile = useMobile();
  const [view, setView] = useState(() => location.hash.slice(1) || (window.innerWidth < 768 ? 'index' : 'about'));
  const [hovered, setHovered] = useState(null);
  const bioRef = useRef(null);
  const [readoutTop, setReadoutTop] = useState(500);

  useEffect(() => {
    const onHash = () => {setView(location.hash.slice(1) || 'about');setHovered(null);};
    window.addEventListener('hashchange', onHash);
    return () => window.removeEventListener('hashchange', onHash);
  }, []);

  useEffect(() => {window.scrollTo(0, 0);}, [view]);

  // Mobile has no About page — always show Index
  useEffect(() => {
    if (isMobile && view === 'about') go('index');
  }, [isMobile, view]);

  // Track bio panel bottom for DiagramReadout positioning
  useEffect(() => {
    if (!bioRef.current) return;
    const update = () => {
      if (bioRef.current) {
        const r = bioRef.current.getBoundingClientRect();
        setReadoutTop(Math.round(r.bottom) + 20);
      }
    };
    update();
    const ro = new ResizeObserver(update);
    ro.observe(bioRef.current);
    return () => ro.disconnect();
  }, [view]);

  const go = (v) => {location.hash = v === 'about' ? '' : v;};
  const openProject = (p) => {location.hash = p.id;};

  const project = view !== 'about' && view !== 'index' ?
  window.PROJECTS.find((p) => p.id === view) : null;
  const isIndex = view === 'index';
  const isAbout = !project && !isIndex;

  let footerLeft = [];

  // bubble appearance globals (read by BubbleNav + bubble backgrounds)
  window.__navGraphic = t.bubbleNavGraphic;
  if (typeof document !== 'undefined') {
    document.documentElement.style.setProperty('--bubble-op', t.bubbleOpacity);
  }


  return (
    <div style={{ fontFamily: FONT }}>
      <DepthCloud />
      <AnimatedEntity />
      <CustomCursor />

      {isAbout && !isMobile &&
      <React.Fragment>
          <BioAbout ref={bioRef} locationStyle={t.locationStyle} />
          <AboutDiagram
          projects={window.PROJECTS}
          locked={t.nodesLocked}
          onOpen={openProject}
          onHover={setHovered}
          hoveredId={hovered ? hovered.id : null} />
          <DiagramReadout p={hovered} top={readoutTop} />
        </React.Fragment>
      }

      {/* Entity 2 stays mounted across pages so it never pops back in */}
      {!isMobile &&
      <KeepAlive active={isAbout}>
          <LargeEntity locked={t.nodesLocked} />
        </KeepAlive>
      }

      {/* Index stays mounted so its images never re-load when returning */}
      {!isMobile &&
      <KeepAlive active={isIndex}>
          <IndexGrid
          cardMode={t.indexCardMode}
          imageLimit={t.imageLimit}
          locked={t.nodesLocked}
          onOpen={openProject}
          onHover={setHovered}
          isMobile={false}
          locationStyle={t.locationStyle} />
        </KeepAlive>
      }

      {isIndex && isMobile &&
      <IndexGrid
        cardMode={t.indexCardMode}
        imageLimit={t.imageLimit}
        locked={t.nodesLocked}
        onOpen={openProject}
        onHover={setHovered}
        isMobile={true}
        locationStyle={t.locationStyle} />
      }

      {isIndex && !isMobile &&
      <React.Fragment>
          <BioShort locationStyle={t.locationStyle} top={19} contact={false} />
          {t.indexCardMode === 'off' && <IndexReadout p={hovered} />}
        </React.Fragment>
      }

      {project &&
      <ProjectPage p={project} locationStyle={t.locationStyle} locked={t.nodesLocked} mobile={isMobile} />
      }

      <Footer left={footerLeft} navPosition={t.navPosition} />

      <TweaksPanel>
        <TweakSection label="Authoring" />
        <TweakToggle label="Lock all positions" value={t.nodesLocked}
        onChange={(v) => setTweak('nodesLocked', v)} />
        <LayoutExport />

        <TweakSection label="Navigation" />
        <TweakRadio label="Nav position"
        value={t.navPosition}
        options={['bottom-left', 'top-right', 'top-center']}
        onChange={(v) => setTweak('navPosition', v)} />

        <TweakSection label="Bubble" />
        <TweakSlider label="Bubble opacity"
        value={t.bubbleOpacity} min={0.3} max={1} step={0.05}
        onChange={(v) => setTweak('bubbleOpacity', v)} />
        <TweakToggle label="Graphic nav glyph" value={t.bubbleNavGraphic}
        onChange={(v) => setTweak('bubbleNavGraphic', v)} />

        <TweakSection label="Live location" />
        <TweakRadio label="Signifier" value={t.locationStyle}
        options={['pulse', 'clock', 'both']}
        onChange={(v) => setTweak('locationStyle', v)} />

        <TweakSection label="Index" />
        <TweakRadio label="Project cards"
        value={t.indexCardMode}
        options={['off', 'title']}
        onChange={(v) => setTweak('indexCardMode', v)} />
        <TweakSlider label="Default preview images"
        value={t.imageLimit} min={1} max={20} step={1}
        onChange={(v) => setTweak('imageLimit', v)} />
      </TweaksPanel>
    </div>);

}

(function () {
  function boot() {
    ReactDOM.createRoot(document.getElementById('root')).render(<App />);
  }
  // Wait for remote content (Supabase) if configured; fall back to bundled data.
  if (window.__remoteReady || !window.SUPABASE_URL) boot();
  else {
    var did = false;
    var go = function () { if (did) return; did = true; boot(); };
    window.addEventListener('remote-content-ready', go, { once: true });
    setTimeout(go, 7000); // safety net
  }
})();